services:
  localkuh:
    build: .
    ports:
      - "3000:3000"
    environment:
      - API_KEY=${API_KEY}
      - TEMPLATE_ID=${TEMPLATE_ID}
      - PRINTER_ID=${PRINTER_ID}
      - PORT=3000
    restart: unless-stopped